#!/bin/bash
set -e

# SecondBrain Kit — Setup Wizard
# Run: chmod +x setup.sh && ./setup.sh

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${BOLD}SecondBrain Kit — Setup${NC}"
echo "AI-powered knowledge management with Obsidian"
echo "=============================================="
echo ""

# --- Check Docker ---
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Docker is not installed.${NC}"
    echo "Install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker info &> /dev/null 2>&1; then
    echo -e "${RED}Docker is not running. Start Docker and try again.${NC}"
    exit 1
fi

echo -e "${GREEN}Docker is ready.${NC}"
echo ""

# --- Gemini API Key ---
echo -e "${BOLD}Step 1/4: Gemini API Key${NC}"
echo "Get your key at: https://aistudio.google.com/apikey"
echo ""
read -p "Gemini API Key: " GEMINI_API_KEY

if [ -z "$GEMINI_API_KEY" ]; then
    echo -e "${RED}API key is required.${NC}"
    exit 1
fi
echo ""

# --- Vault Path ---
echo -e "${BOLD}Step 2/4: Vault Location${NC}"
echo "Where should your knowledge vault be stored?"
echo "This is where Obsidian will read your notes from."
echo ""
DEFAULT_VAULT="$HOME/SecondBrain"
read -p "Vault path [$DEFAULT_VAULT]: " VAULT_INPUT
VAULT_PATH="${VAULT_INPUT:-$DEFAULT_VAULT}"

# Expand ~ if present
VAULT_PATH="${VAULT_PATH/#\~/$HOME}"

echo ""

# --- Telegram (optional) ---
echo -e "${BOLD}Step 3/4: Telegram Notifications (optional)${NC}"
echo "Get notified when notes are renamed or merged."
echo "Skip if you don't need this."
echo ""
read -p "Telegram Bot Token (Enter to skip): " TG_TOKEN

TG_CHAT_ID=""
if [ -n "$TG_TOKEN" ]; then
    echo ""
    echo "To find your Chat ID, message @userinfobot on Telegram."
    read -p "Telegram Chat ID: " TG_CHAT_ID
fi
echo ""

# --- WebUI Password ---
echo -e "${BOLD}Step 4/4: Knowledge Graph WebUI${NC}"
echo "Set a password for the LightRAG web interface (port 9621)."
echo ""
read -p "WebUI username [admin]: " WEBUI_USER
WEBUI_USER="${WEBUI_USER:-admin}"
read -s -p "WebUI password [auto-generated]: " WEBUI_PASS
echo ""
if [ -z "$WEBUI_PASS" ]; then
    WEBUI_PASS=$(openssl rand -hex 8)
    echo -e "Generated password: ${BOLD}${WEBUI_PASS}${NC}"
fi

# --- Generate secrets ---
API_KEY=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 16)

# --- Create vault from template ---
echo ""
echo -e "${BOLD}Setting up vault...${NC}"

if [ -d "$VAULT_PATH" ]; then
    echo -e "${YELLOW}Vault directory already exists: $VAULT_PATH${NC}"
    echo "Existing files will be preserved. Template files will be added if missing."
else
    mkdir -p "$VAULT_PATH"
fi

# Copy template files (don't overwrite existing)
cp -rn vault-template/ "$VAULT_PATH/" 2>/dev/null || {
    # macOS cp -n doesn't support -r well, fallback
    for item in vault-template/*; do
        base=$(basename "$item")
        if [ ! -e "$VAULT_PATH/$base" ]; then
            cp -r "$item" "$VAULT_PATH/"
        fi
    done
    # Copy hidden files
    for item in vault-template/.*; do
        base=$(basename "$item")
        [ "$base" = "." ] || [ "$base" = ".." ] && continue
        if [ ! -e "$VAULT_PATH/$base" ]; then
            cp -r "$item" "$VAULT_PATH/"
        fi
    done
}

echo -e "${GREEN}Vault ready: $VAULT_PATH${NC}"

# Init git in vault if not already
if [ ! -d "$VAULT_PATH/.git" ]; then
    echo "Initializing git in vault..."
    (cd "$VAULT_PATH" && git init && git add -A && git commit -m "init: SecondBrain vault" --allow-empty)
    echo -e "${GREEN}Git initialized in vault.${NC}"
fi

# --- Write .env ---
echo ""
echo -e "${BOLD}Writing .env...${NC}"

cat > .env << ENVEOF
# Generated by setup.sh on $(date +%Y-%m-%d)
GEMINI_API_KEY=${GEMINI_API_KEY}
SECONDBRAIN_API_KEY=${API_KEY}

VAULT_PATH=/app/vault
INBOX_DIR_NAME=_inbox

LIGHTRAG_WORKING_DIR=/app/vault/.lightrag
LIGHTRAG_LLM_MODEL=gemini-2.5-pro
LIGHTRAG_EMBEDDING_MODEL=gemini-embedding-001
LIGHTRAG_EMBEDDING_DIMENSIONS=3072
LIGHTRAG_CHUNK_SIZE=1200
LIGHTRAG_VECTOR_STORAGE=QdrantVectorDBStorage

QDRANT_URL=http://secondbrain-qdrant:6333

LLM_MODEL=gemini-2.5-pro
MERGE_THRESHOLD=0.85

WEBUI_USERNAME=${WEBUI_USER}
WEBUI_PASSWORD=${WEBUI_PASS}
WEBUI_JWT_SECRET=${JWT_SECRET}
ENVEOF

# Add Telegram if configured
if [ -n "$TG_TOKEN" ]; then
    echo "" >> .env
    echo "TELEGRAM_BOT_TOKEN=${TG_TOKEN}" >> .env
    echo "TELEGRAM_DM_CHAT_ID=${TG_CHAT_ID}" >> .env
fi

# Write HOST_VAULT_PATH for docker-compose volume mount
echo "" >> .env
echo "HOST_VAULT_PATH=${VAULT_PATH}" >> .env

echo -e "${GREEN}.env created.${NC}"

# --- Start ---
echo ""
echo -e "${BOLD}Starting SecondBrain...${NC}"
docker compose up -d --build

echo ""
echo "=============================================="
echo -e "${GREEN}SecondBrain Kit is running!${NC}"
echo ""
echo "  Vault:  $VAULT_PATH"
echo "  API:    http://localhost:8789"
echo "  WebUI:  http://localhost:9621"
echo "  API Key: $API_KEY"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. Open Obsidian and select '$VAULT_PATH' as vault"
echo "  2. Install the 'Obsidian Git' community plugin for sync"
echo "  3. Drop .md files into $VAULT_PATH/_inbox/ — the daemon processes them"
echo "  4. Use the API:"
echo "     curl -X POST http://localhost:8789/search \\"
echo "       -H 'X-Api-Key: $API_KEY' \\"
echo "       -d '{\"query\": \"test\"}'"
echo ""
echo "  See docs/SETUP.md for detailed instructions."
echo "  See docs/VPS-DEPLOY.md for remote server deployment."
echo ""
